/* eslint-disable no-restricted-globals */
import { clientsClaim } from "workbox-core";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { NetworkFirst, StaleWhileRevalidate } from "workbox-strategies";

clientsClaim();

// This is a crucial step. It tells the new service worker to activate
// as soon as it's finished installing, rather than waiting for the
// existing service worker to stop controlling clients.
self.skipWaiting();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This is still important for the offline fallback.
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell.
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith("/_")) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);


// --- THIS IS THE KEY CHANGE ---
// An example runtime caching route for requests that aren't handled by the
// precache, such as requests to Google Fonts.
// We are using StaleWhileRevalidate for fonts, but NetworkFirst for our assets.
registerRoute(
  ({ url }) => url.origin === self.location.origin && (
    url.pathname.endsWith('.png') ||
    url.pathname.endsWith('.jpg') ||
    url.pathname.endsWith('.svg')
  ),
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      // Ensure that once this runtime cache is full, the oldest images are removed.
      // new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Use NetworkFirst for the main application assets (JS, CSS) and navigations.
registerRoute(
    ({ request }) =>
      request.mode === 'navigate' ||
      request.destination === 'script' ||
      request.destination === 'style',
    new NetworkFirst({
      cacheName: 'app-shell',
      networkTimeoutSeconds: 5, // Fallback to cache if network takes too long
    })
);